services:
  snp_automate_2023:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - TAG=humble-5.0
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      # NVIDIA_DRIVER_CAPABILITIES: all
      ROS_LOG_DIR: /tmp/.ros
      ROS_LOCALHOST_ONLY: $ROS_LOCALHOST_ONLY
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
    container_name: snp_automate_2023
    image: ghcr.io/ros-industrial-consortium/snp_automate_2023:humble-master
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    user: ${CURRENT_UID}  # CURRENT_UID=$(id -u):$(id -g)
    group_add:
      - sudo
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/hosts:/etc/hosts
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
      - /dev:/dev
      - alloy-ros-logs:/tmp/.ros
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
  # Driver
  micro-ros-agent:
    environment:
      ROS_LOG_DIR: /tmp
      ROS_LOCALHOST_ONLY: $ROS_LOCALHOST_ONLY
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
    container_name: micro-ros-agent
    image: microros/micro-ros-agent:humble
    command: udp4 --port 8888
    stdin_open: true
    tty: true
    network_mode: host
 
  loki:
    image: grafana/loki:3.0.0
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
  prometheus:
    image: prom/prometheus:v2.47.0
    command:
      - --web.enable-remote-write-receiver
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
    entrypoint:
      - sh
      - -euc
      - |
        mkdir -p /etc/grafana/provisioning/datasources
        cat <<EOF > /etc/grafana/provisioning/datasources/ds.yaml
        apiVersion: 1
        datasources:
        - name: Loki
          type: loki
          access: proxy
          orgId: 1
          url: http://loki:3100
          basicAuth: false
          isDefault: false
          version: 1
          editable: false
        - name: Prometheus
          type: prometheus
          orgId: 1
          url: http://prometheus:9090
          basicAuth: false
          isDefault: true
          version: 1
          editable: false
        EOF
        /run.sh
    image: grafana/grafana:11.0.0
    ports:
      - "3000:3000"

  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    command: ["run", "--server.http.listen-addr=0.0.0.0:12345", "/config.alloy"]

    ports:
      - "12345:12345"  # expose Alloy's debug UI

    volumes:
      - ./config.alloy:/config.alloy
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
      - alloy-ros-logs:/ros_logs:ros
    depends_on:
      - loki



  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    network_mode: "host"
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro


volumes:
  grafana-storage: