services:
  snp_automate_2023:
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        - TAG=humble-5.0
    environment:
      DISPLAY: $DISPLAY
      XAUTHORITY: $XAUTHORITY
      # NVIDIA_DRIVER_CAPABILITIES: all
      ROS_LOG_DIR: /tmp/.ros
      ROS_LOCALHOST_ONLY: $ROS_LOCALHOST_ONLY
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
    container_name: snp_automate_2023
    image: ghcr.io/ros-industrial-consortium/snp_automate_2023:humble-master
    stdin_open: true
    tty: true
    network_mode: host
    privileged: true
    user: ${CURRENT_UID}  # CURRENT_UID=$(id -u):$(id -g)
    group_add:
      - sudo
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - /etc/hosts:/etc/hosts
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
      - /etc/shadow:/etc/shadow:ro
      - /dev:/dev
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
  # Driver
  micro-ros-agent:
    environment:
      ROS_LOG_DIR: /tmp
      ROS_LOCALHOST_ONLY: $ROS_LOCALHOST_ONLY
      ROS_DOMAIN_ID: $ROS_DOMAIN_ID
    container_name: micro-ros-agent
    image: microros/micro-ros-agent:humble
    command: udp4 --port 8888
    stdin_open: true
    tty: true
    network_mode: host
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - loki

  loki:
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml


  alloy:
    image: grafana/alloy:latest
    container_name: alloy
    # command: ["run", "--config.file=/config.alloy"]
    command: ["run", "/config.alloy"]

    volumes:
      - ./config.alloy:/config.alloy
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - loki


  node_exporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    network_mode: "host"
    pid: "host"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro


volumes:
  grafana-storage: